const products = [
  { name: "CUSTOMISED CAP", image: "https://dreamland-of-fantasies.github.io/website/photos/KA7.jpeg", price: 299, category: ["kids", "trending"] },
  { name: "CROSS BODY SLING (two charm/initial)", image: "https://dreamland-of-fantasies.github.io/website/photos/KA6.jpeg", price: 599, category: ["kids", "trending"] },
  { name: "WAIST POUCH (two charm/initial)", image: "https://dreamland-of-fantasies.github.io/website/photos/KA3.jpeg", price: 599, category: ["kids", "trending"] },
  { name: "VISOR CAPS (two charm/initial)", image: "https://dreamland-of-fantasies.github.io/website/photos/KA1.jpeg", price: 399, category: ["kids", "trending"] },
  { name: "ADDITIONAL CHARMS", image: "https://dreamland-of-fantasies.github.io/website/photos/K7.jpeg", price: 70, category: ["kids"] },
  { name: "PERSONALISED FOLDER", image: "https://dreamland-of-fantasies.github.io/website/photos/K5.jpeg", price: 399, category: ["kids"] },
  { name: "PERSONALIZED JELLY BAG (three charm/initial)", image: "https://dreamland-of-fantasies.github.io/website/photos/K4.jpeg", price: 649, category: ["kids"] },
  { name: "SET OF 4 NECKPILLOW,EYEMASK,PASSPORT COVER,LUGGAGE TAG (individual also available)", image: "https://dreamland-of-fantasies.github.io/website/photos/K2.jpeg", price: 849, category: ["kids"] },
  { name: "COMPLETE FULL ROMPER (REFER COLLAGE FOR PRICES)", image: "https://dreamland-of-fantasies.github.io/website/photos/K.jpeg", price: 1100, category: ["kids"] },
  { name: "CUSTOMISED TUMBLER (350 mL)", image: "https://dreamland-of-fantasies.github.io/website/photos/A7.jpeg", price: 599, category: ["trending"] },
  { name: "PASTEL PASSPORT COVER", image: "https://dreamland-of-fantasies.github.io/website/photos/A5.jpeg", price: 499, category: ["trending"] },
  { name: "TRAVELLING ESSENTIAL COMBO", image: "https://dreamland-of-fantasies.github.io/website/photos/A4.jpeg", price: 1199, category: ["kids"] },
  { name: "SET OF 3 NECKPILLOW,EYEMASK,LUGGAGE TAG", image: "https://dreamland-of-fantasies.github.io/website/photos/A3.jpeg", price: 649, category: ["trending"] },
  { name: "BRANDED PERSONALISED TOWEL", image: "https://dreamland-of-fantasies.github.io/website/photos/A2.jpeg", price: 749, category: ["trending"] },
  { name: "PASSPORT COVER (3 charms)",  image: "https://dreamland-of-fantasies.github.io/website/photos/A.jpeg",  price: 499, category: ["trending"] },
];
