const products = [
  { name: "KA7", image: "https://dreamland-of-fantasies.github.io/website/photos/KA7.jpeg", price: 0, category: ["kids", "trending"] },
  { name: "KA6", image: "https://dreamland-of-fantasies.github.io/website/photos/KA6.jpeg", price: 0, category: ["kids", "trending"] },
  { name: "KA3", image: "https://dreamland-of-fantasies.github.io/website/photos/KA3.jpeg", price: 0, category: ["kids", "trending"] },
  { name: "KA1", image: "https://dreamland-of-fantasies.github.io/website/photos/KA1.jpeg", price: 0, category: ["kids", "trending"] },
  { name: "K7", image: "https://dreamland-of-fantasies.github.io/website/photos/K7.jpeg", price: 0, category: ["kids"] },
  { name: "K5", image: "https://dreamland-of-fantasies.github.io/website/photos/K5.jpeg", price: 0, category: ["kids"] },
  { name: "K4", image: "https://dreamland-of-fantasies.github.io/website/photos/K4.jpeg", price: 0, category: ["kids"] },
  { name: "K3", image: "https://dreamland-of-fantasies.github.io/website/photos/K3.jpeg", price: 0, category: ["kids"] },
  { name: "K2", image: "https://dreamland-of-fantasies.github.io/website/photos/K2.jpeg", price: 0, category: ["kids"] },
  { name: "K", image: "https://dreamland-of-fantasies.github.io/website/photos/K.jpeg", price: 0, category: ["kids"] },
  { name: "A7", image: "https://dreamland-of-fantasies.github.io/website/photos/A7.jpeg", price: 0, category: ["trending"] },
  { name: "A5", image: "https://dreamland-of-fantasies.github.io/website/photos/A5.jpeg", price: 0, category: ["trending"] },
  { name: "A4", image: "https://dreamland-of-fantasies.github.io/website/photos/A4.jpeg", price: 0, category: ["trending"] },
  { name: "A3", image: "https://dreamland-of-fantasies.github.io/website/photos/A3.jpeg", price: 0, category: ["trending"] },
  { name: "A2", image: "https://dreamland-of-fantasies.github.io/website/photos/A2.jpeg", price: 0, category: ["trending"] },
  { name: "A",  image: "https://dreamland-of-fantasies.github.io/website/photos/A.jpeg",  price: 0, category: ["trending"] },
];
